apiVersion: skaffold/v4beta12
kind: Config
metadata:
  name: spring-boot-skaffold-
build:
  artifacts:
    - image: hendisantika/spring-skaffold
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
    - k8s/deployment.yaml
    - k8s/service.yaml
