apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-skaffold
spec:
  selector:
    matchLabels:
      app: spring-skaffold
  template:
    metadata:
      labels:
        app: spring-skaffold
    spec:
      containers:
        - name: spring-skaffold
          image: hendisantika/spring-skaffold
          envFrom:
            - configMapRef:
                name: spring-skaffold-envs
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
